/**
 * VFS legacy-row supersede semantics.
 *
 * Production failure: a fresh authoritative TV episode publication was
 * rejected by historical VFS state. Legacy rows materialized before the
 * TorrentFile identity refactor carry NULL torrent_file_id, the parent
 * torrent info_hash, an explicit file_index, and a hydrated size. The
 * authoritative publication carries a different info_hash, no file_index,
 * and a TorrentFile-backed identity (torrent_file_id, internalPath, size).
 *
 * The materialize path must atomically supersede the legacy row in place
 * when the new authoritative publication arrives, preserving the published
 * canonical_path so the library alias (and any downstream WebDAV / Plex /
 * Jellyfin references) remains stable. Authoritative rows must remain
 * fail-closed against differing identities and idempotent against identical
 * identities.
 */

import assert from 'node:assert/strict';
import test from 'node:test';

import { createDiscoveryCache } from '../src/lib/discovery/cache.js';
import { materializeVfsEntry } from '../src/lib/vfs/materialize.js';

const PARENT_INFO_HASH = '18f1fa740652ff438b261080073ba4b8171e9428';
const LEGACY_SEASON_PACK_INFO_HASH = '33c59643327641d632ca814532f8aa0b746bdb43';

function createControlPlaneStoreMock(torrentFiles) {
  const map = new Map(torrentFiles.map((tf) => [tf.id, tf]));
  return {
    getTorrentFile(id) {
      return map.get(id) || null;
    },
  };
}

function legacySeasonPackHandoff({ season, episode, size }) {
  return {
    mediaId: 'tt10986410',
    mediaType: 'tv',
    season,
    episode,
    releaseKey: `${LEGACY_SEASON_PACK_INFO_HASH}:${episode}`,
    infoHash: LEGACY_SEASON_PACK_INFO_HASH,
    fileIndex: episode,
    filename: `Ted Lasso - S0${season}E0${episode}.mkv`,
    canonicalTitle: 'Ted Lasso',
    // No torrentFileId — legacy row was materialized before TorrentFile binding.
    torrentFileId: null,
    provider: 'torbox',
    providerState: 'cached',
    identityTier: 'Verified',
    resolutionState: 'confirmed',
    selectionReason: 'legacy',
    selectedAt: 1_788_000_000_000,
  };
}

function authoritativeHandoff({ season, episode, torrentFileId, size }) {
  return {
    mediaId: 'tt10986410',
    mediaType: 'tv',
    season,
    episode,
    releaseKey: `${PARENT_INFO_HASH}:torrent`,
    infoHash: PARENT_INFO_HASH,
    fileIndex: null,
    filename: `Тед Лассо.S0${season}.WEB-DL.2160p/Тед Лассо.S0${season}E0${episode}.WEB-DL.2160p.mkv`,
    canonicalTitle: 'Ted Lasso',
    torrentFileId,
    provider: 'torbox',
    providerState: 'cached',
    identityTier: 'Verified',
    resolutionState: 'confirmed',
    selectionReason: 'authoritative',
    selectedAt: 1_788_270_000_000,
  };
}

function tedE2TorrentFile() {
  return {
    id: 'tf_ecbd6de5-9f28-4002-a682-a38960f00c93',
    infoHash: PARENT_INFO_HASH,
    internalPath: 'Тед Лассо.S01.WEB-DL.2160p/Тед Лассо.S01E02.WEB-DL.2160p.mkv',
    size: 5_691_921_896,
    createdAt: 1_788_270_000_000,
  };
}

function tedE7TorrentFile() {
  return {
    id: 'tf_4d33b065-3c8f-4889-a7ee-c7474771e9b7',
    infoHash: PARENT_INFO_HASH,
    internalPath: 'Тед Лассо.S01.WEB-DL.2160p/Тед Лассо.S01E07.WEB-DL.2160p.mkv',
    size: 5_100_000_001,
    createdAt: 1_788_270_000_000,
  };
}

function seedLegacyRow(cache, { season, episode, size }) {
  // The legacy path was computed from the (older) canonical title and
  // published as the user's library alias. It must not be regenerated by
  // the supersede.
  return cache.createVfsTvEntry({
    mediaId: 'tt10986410',
    season,
    episode,
    releaseKey: `${LEGACY_SEASON_PACK_INFO_HASH}:${episode}`,
    infoHash: LEGACY_SEASON_PACK_INFO_HASH,
    fileIndex: episode,
    canonicalPath: `TV/Ted Lasso/Season 0${season}/Ted Lasso - S0${season}E0${episode}.mkv`,
    torrentFileId: null,
    size,
    createdAt: 1_788_000_000_000,
    updatedAt: 1_788_000_000_000,
  });
}

test('materializeVfsEntry supersedes a legacy TV row when authoritative publication arrives', (t) => {
  const cache = createDiscoveryCache();
  t.after(() => cache.close());

  const legacy = seedLegacyRow(cache, { season: 1, episode: 2, size: 17_115_254_885 });
  assert.equal(legacy.torrentFileId, null, 'precondition: legacy row has NULL torrent_file_id');
  assert.equal(legacy.size, 17_115_254_885, 'precondition: legacy size preserved from hydration');

  const controlPlaneStore = createControlPlaneStoreMock([tedE2TorrentFile()]);

  const before = 1_788_270_500_000;
  const after = 1_788_270_500_500;
  const entry = materializeVfsEntry(
    cache,
    authoritativeHandoff({
      season: 1,
      episode: 2,
      torrentFileId: tedE2TorrentFile().id,
      size: tedE2TorrentFile().size,
    }),
    controlPlaneStore,
    () => before,
    { allowLegacy: false },
  );

  // Resulting authoritative row
  assert.equal(entry.mediaId, 'tt10986410');
  assert.equal(entry.season, 1);
  assert.equal(entry.episode, 2);
  assert.equal(entry.torrentFileId, tedE2TorrentFile().id, 'torrent_file_id from TorrentFile');
  assert.equal(entry.infoHash, PARENT_INFO_HASH, 'infoHash from TorrentFile');
  assert.equal(entry.size, tedE2TorrentFile().size, 'size from TorrentFile');
  assert.equal(entry.fileIndex, null, 'file_index dropped; TorrentFile is the authority');
  assert.equal(
    entry.canonicalPath,
    'TV/Ted Lasso/Season 01/Ted Lasso - S01E02.mkv',
    'canonical_path preserved verbatim so the published library alias stays stable',
  );
  assert.equal(entry.releaseKey, `${PARENT_INFO_HASH}:torrent`);
  assert.ok(entry.updatedAt >= before && entry.updatedAt <= after);

  // Persisted state must match the returned entry
  const persisted = cache.getVfsTvEntry('tt10986410', 1, 2);
  assert.equal(persisted.torrentFileId, tedE2TorrentFile().id);
  assert.equal(persisted.size, tedE2TorrentFile().size);
  assert.equal(persisted.canonicalPath, entry.canonicalPath);
  assert.equal(persisted.infoHash, PARENT_INFO_HASH);

  // No second row for the same logical key (atomic supersede, no duplicate)
  const all = cache.listVfsTvEntries().filter((e) =>
    e.mediaId === 'tt10986410' && e.season === 1 && e.episode === 2,
  );
  assert.equal(all.length, 1, 'legacy row superseded in place — no duplicate');
});

test('materializeVfsEntry is idempotent when an identical authoritative publication is replayed', (t) => {
  const cache = createDiscoveryCache();
  t.after(() => cache.close());

  const controlPlaneStore = createControlPlaneStoreMock([tedE2TorrentFile()]);

  // First publication supersedes the legacy row
  const first = materializeVfsEntry(
    cache,
    authoritativeHandoff({
      season: 1,
      episode: 2,
      torrentFileId: tedE2TorrentFile().id,
      size: tedE2TorrentFile().size,
    }),
    controlPlaneStore,
    () => 1_788_270_000_000,
    { allowLegacy: false },
  );

  // Second identical publication (e.g. Seerr resend, retry, or duplicate request)
  const second = materializeVfsEntry(
    cache,
    authoritativeHandoff({
      season: 1,
      episode: 2,
      torrentFileId: tedE2TorrentFile().id,
      size: tedE2TorrentFile().size,
    }),
    controlPlaneStore,
    () => 1_788_270_500_000,
    { allowLegacy: false },
  );

  assert.equal(second.torrentFileId, first.torrentFileId);
  assert.equal(second.size, first.size);
  assert.equal(second.infoHash, first.infoHash);
  assert.equal(second.canonicalPath, first.canonicalPath);
  assert.equal(second.createdAt, first.createdAt, 'createdAt is preserved on idempotent replay');

  const all = cache.listVfsTvEntries().filter((e) =>
    e.mediaId === 'tt10986410' && e.season === 1 && e.episode === 2,
  );
  assert.equal(all.length, 1, 'replay does not create a second row');
});

test('materializeVfsEntry remains fail-closed when an existing authoritative row has a differing TorrentFile identity', (t) => {
  const cache = createDiscoveryCache();
  t.after(() => cache.close());

  // Seed an existing authoritative row with a different TorrentFile identity
  const firstTf = tedE2TorrentFile();
  const original = cache.createVfsTvEntry({
    mediaId: 'tt10986410',
    season: 1,
    episode: 2,
    releaseKey: `${firstTf.infoHash}:torrent`,
    infoHash: firstTf.infoHash,
    fileIndex: null,
    canonicalPath: 'TV/Ted Lasso/Season 01/Ted Lasso - S01E02.mkv',
    torrentFileId: firstTf.id,
    size: firstTf.size,
    createdAt: 1_788_270_000_000,
    updatedAt: 1_788_270_000_000,
  });

  // Build a second TorrentFile with a different identity (same infoHash, but
  // different internalPath/size, and a different torrentFileId).
  const conflictingTf = {
    id: 'tf_different-4d33b065-3c8f-4889-a7ee-c7474771e9b7',
    infoHash: firstTf.infoHash,
    internalPath: 'different/path/file.mkv',
    size: firstTf.size + 1,
    createdAt: 1_788_270_000_000,
  };
  const controlPlaneStore = createControlPlaneStoreMock([firstTf, conflictingTf]);

  assert.throws(
    () => materializeVfsEntry(
      cache,
      authoritativeHandoff({
        season: 1,
        episode: 2,
        torrentFileId: conflictingTf.id,
        size: conflictingTf.size,
      }),
      controlPlaneStore,
      () => 1_788_280_000_000,
      { allowLegacy: false },
    ),
    /conflicts with TorrentFile/,
    'differing authoritative identities must remain fail-closed',
  );

  const persisted = cache.getVfsTvEntry('tt10986410', 1, 2);
  assert.equal(persisted.torrentFileId, original.torrentFileId, 'existing authoritative row is untouched');
  assert.equal(persisted.size, original.size);
  assert.equal(persisted.updatedAt, original.updatedAt);
});

test('materializeVfsEntry inserts a new authoritative row for an episode that has no legacy state', (t) => {
  const cache = createDiscoveryCache();
  t.after(() => cache.close());

  const controlPlaneStore = createControlPlaneStoreMock([tedE7TorrentFile()]);

  // No legacy row for E07 (a previously-unpublished episode)
  assert.equal(cache.getVfsTvEntry('tt10986410', 1, 7), null);

  const entry = materializeVfsEntry(
    cache,
    authoritativeHandoff({
      season: 1,
      episode: 7,
      torrentFileId: tedE7TorrentFile().id,
      size: tedE7TorrentFile().size,
    }),
    controlPlaneStore,
    () => 1_788_270_000_000,
    { allowLegacy: false },
  );

  assert.equal(entry.torrentFileId, tedE7TorrentFile().id);
  assert.equal(entry.size, tedE7TorrentFile().size);
  assert.equal(entry.infoHash, PARENT_INFO_HASH);
  assert.equal(entry.fileIndex, null);
  assert.match(entry.canonicalPath, /TV\/Ted Lasso\/Season 01\/Ted Lasso - S01E07\.mkv/);
});
