import type { ReleaseResult, TitleResult } from '@/types/api';

export const mockTitles: TitleResult[] = [
  {
    id: 'tt2085059',
    type: 'series',
    title: 'Black Mirror',
    posterUrl: 'https://example.com/poster.jpg',
    backdropUrl: null,
    year: 2011,
    overview: 'Stand-alone dramas exploring twisted high-tech futures.',
  },
  {
    id: 'tt0944947',
    type: 'series',
    title: 'Game of Thrones',
    posterUrl: null,
    backdropUrl: null,
    year: 2011,
    overview: null,
  },
];

export const mockReleases: ReleaseResult[] = [
  {
    infoHash: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    fileIndex: null,
    releaseKey: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:torrent',
    title: 'Black Mirror',
    filename: 'Black.Mirror.S07E03.2160p.WEB-DL.DV.HDR10.mkv',
    size: 8589934592,
    resolution: '2160p',
    quality: 'WEB-DL',
    codec: 'x265',
    hdr: 'true',
    audio: 'DTS-HD',
    releaseGroup: 'NTb',
    year: 2023,
    season: 7,
    episode: 3,
    confidence: 0.92,
    score: 0.85,
    components: {
      relevance: 1,
      quality: 0.95,
      releaseConfidence: 0.92,
      identityConfidence: 0.9,
      providerAvailability: 1,
      episodeMatch: 1,
    },
    providers: {
      torbox: { cached: true, evidence: ['usenet'] },
    },
    providerObservations: [{
      provider: 'torbox', kind: 'authoritative', state: 'cached', cached: true,
      freshness: 'fresh', fresh: true, evidence: ['usenet'],
    }],
    media: [],
    _source: 'corpus',
  },
  {
    infoHash: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    fileIndex: null,
    releaseKey: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb:torrent',
    title: 'Black Mirror',
    filename: 'Black.Mirror.S07E03.1080p.WEB-DL.mkv',
    size: 4294967296,
    resolution: '1080p',
    quality: 'WEB-DL',
    codec: 'x264',
    hdr: null,
    audio: 'AAC',
    releaseGroup: 'AMZN',
    year: 2023,
    season: 7,
    episode: 3,
    confidence: 0.88,
    score: 0.72,
    components: {
      relevance: 1,
      quality: 0.75,
      releaseConfidence: 0.88,
      identityConfidence: 0.85,
      providerAvailability: 0.5,
      episodeMatch: 1,
    },
    providers: {
      torbox: { cached: false, evidence: null },
    },
    providerObservations: [{
      provider: 'torbox', kind: 'authoritative', state: 'uncached', cached: false,
      freshness: 'fresh', fresh: true, evidence: null,
    }],
    media: [],
    _source: 'live',
  },
  {
    infoHash: 'cccccccccccccccccccccccccccccccccccccccc',
    fileIndex: null,
    releaseKey: 'cccccccccccccccccccccccccccccccccccccccc:torrent',
    title: 'Black Mirror',
    filename: 'Black.Mirror.S07E03.720p.HDTV.mkv',
    size: 1073741824,
    resolution: '720p',
    quality: 'HDTV',
    codec: 'x264',
    hdr: null,
    audio: 'MP3',
    releaseGroup: 'KILLERS',
    year: 2023,
    season: 7,
    episode: 3,
    confidence: 0.75,
    score: 0.45,
    components: {
      relevance: 0.9,
      quality: 0.4,
      releaseConfidence: 0.75,
      identityConfidence: 0.8,
      providerAvailability: 0,
      episodeMatch: 1,
    },
    providers: {},
    providerObservations: [],
    media: [],
    _source: 'corpus',
  },
  {
    infoHash: 'dddddddddddddddddddddddddddddddddddddddd',
    fileIndex: null,
    releaseKey: 'dddddddddddddddddddddddddddddddddddddddd:torrent',
    title: 'Black Mirror',
    filename: 'Black.Mirror.S07E03.1080p.BluRay.mkv',
    size: 6442450944,
    resolution: '1080p',
    quality: 'BluRay',
    codec: 'x264',
    hdr: null,
    audio: 'DTS',
    releaseGroup: 'SPARK',
    year: 2023,
    season: 7,
    episode: 3,
    confidence: 0.82,
    score: 0.68,
    components: {
      relevance: 1,
      quality: 0.8,
      releaseConfidence: 0.82,
      identityConfidence: 0.88,
      providerAvailability: 0.6,
      episodeMatch: 1,
    },
    providers: {
      torbox: { cached: true, evidence: ['usenet'] },
    },
    providerObservations: [{
      provider: 'torbox', kind: 'authoritative', state: 'cached', cached: true,
      freshness: 'fresh', fresh: true, evidence: ['usenet'],
    }],
    media: [],
    _source: 'corpus',
  },
  {
    infoHash: 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    fileIndex: null,
    releaseKey: 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee:torrent',
    title: 'Black Mirror',
    filename: 'Black.Mirror.S07E03.720p.WEB-DL.mkv',
    size: 2147483648,
    resolution: '720p',
    quality: 'WEB-DL',
    codec: 'x264',
    hdr: null,
    audio: 'AAC',
    releaseGroup: 'AMZN',
    year: 2023,
    season: 7,
    episode: 3,
    confidence: 0.78,
    score: 0.55,
    components: {
      relevance: 1,
      quality: 0.6,
      releaseConfidence: 0.78,
      identityConfidence: 0.82,
      providerAvailability: 0.4,
      episodeMatch: 1,
    },
    providers: {
      torbox: { cached: false, evidence: null },
    },
    providerObservations: [{
      provider: 'torbox', kind: 'authoritative', state: 'uncached', cached: false,
      freshness: 'fresh', fresh: true, evidence: null,
    }],
    media: [],
    _source: 'live',
  },
  {
    infoHash: 'ffffffffffffffffffffffffffffffffffffffff',
    fileIndex: null,
    releaseKey: 'ffffffffffffffffffffffffffffffffffffffff:torrent',
    title: 'Black Mirror',
    filename: 'Black.Mirror.S07E03.480p.HDTV.mkv',
    size: 751619276,
    resolution: '480p',
    quality: 'HDTV',
    codec: 'x264',
    hdr: null,
    audio: 'MP3',
    releaseGroup: 'KILLERS',
    year: 2023,
    season: 7,
    episode: 3,
    confidence: 0.6,
    score: 0.30,
    components: {
      relevance: 0.8,
      quality: 0.25,
      releaseConfidence: 0.6,
      identityConfidence: 0.7,
      providerAvailability: 0,
      episodeMatch: 1,
    },
    providers: {},
    providerObservations: [],
    media: [],
    _source: 'corpus',
  },
  {
    infoHash: '1111111111111111111111111111111111111111',
    fileIndex: null,
    releaseKey: '1111111111111111111111111111111111111111:torrent',
    title: 'Black Mirror',
    filename: 'Black.Mirror.S07E03.1080p.WEB-DL.LOW.mkv',
    size: 1610612736,
    resolution: '1080p',
    quality: 'WEB-DL',
    codec: 'x264',
    hdr: null,
    audio: 'AAC',
    releaseGroup: 'RARBG',
    year: 2023,
    season: 7,
    episode: 3,
    confidence: 0.7,
    score: 0.40,
    components: {
      relevance: 1,
      quality: 0.5,
      releaseConfidence: 0.7,
      identityConfidence: 0.75,
      providerAvailability: 0.3,
      episodeMatch: 1,
    },
    providers: {
      torbox: { cached: false, evidence: null },
    },
    providerObservations: [{
      provider: 'torbox', kind: 'authoritative', state: 'uncached', cached: false,
      freshness: 'fresh', fresh: true, evidence: null,
    }],
    media: [],
    _source: 'live',
  },
];
