import type { ReleaseResult, TitleResult } from '@/types/api';

export const mockTitles: TitleResult[] = [
  {
    id: 'tt2085059',
    type: 'series',
    name: 'Black Mirror',
    poster: 'https://example.com/poster.jpg',
    year: '2011-',
    description: 'Stand-alone dramas exploring twisted high-tech futures.',
  },
  {
    id: 'tt0944947',
    type: 'series',
    name: 'Game of Thrones',
    poster: null,
    year: '2011-2019',
    description: null,
  },
];

export const mockReleases: ReleaseResult[] = [
  {
    infoHash: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    fileIndex: null,
    title: 'Black Mirror',
    filename: 'Black.Mirror.S07E03.2160p.WEB-DL.DV.HDR10.mkv',
    size: 8589934592,
    resolution: '2160p',
    quality: 'WEB-DL',
    codec: 'x265',
    hdr: 'true',
    audio: 'DTS-HD',
    releaseGroup: 'NTb',
    year: 2023,
    season: 7,
    episode: 3,
    confidence: 0.92,
    score: 0.85,
    components: {
      relevance: 1,
      quality: 0.95,
      releaseConfidence: 0.92,
      identityConfidence: 0.9,
      providerAvailability: 1,
      episodeMatch: 1,
    },
    providers: {
      torbox: { cached: true, evidence: ['usenet'] },
    },
    media: [],
    _source: 'corpus',
  },
  {
    infoHash: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    fileIndex: null,
    title: 'Black Mirror',
    filename: 'Black.Mirror.S07E03.1080p.WEB-DL.mkv',
    size: 4294967296,
    resolution: '1080p',
    quality: 'WEB-DL',
    codec: 'x264',
    hdr: null,
    audio: 'AAC',
    releaseGroup: 'AMZN',
    year: 2023,
    season: 7,
    episode: 3,
    confidence: 0.88,
    score: 0.72,
    components: {
      relevance: 1,
      quality: 0.75,
      releaseConfidence: 0.88,
      identityConfidence: 0.85,
      providerAvailability: 0.5,
      episodeMatch: 1,
    },
    providers: {
      torbox: { cached: false, evidence: null },
    },
    media: [],
    _source: 'live',
  },
  {
    infoHash: 'cccccccccccccccccccccccccccccccccccccccc',
    fileIndex: null,
    title: 'Black Mirror',
    filename: 'Black.Mirror.S07E03.720p.HDTV.mkv',
    size: 1073741824,
    resolution: '720p',
    quality: 'HDTV',
    codec: 'x264',
    hdr: null,
    audio: 'MP3',
    releaseGroup: 'KILLERS',
    year: 2023,
    season: 7,
    episode: 3,
    confidence: 0.75,
    score: 0.45,
    components: {
      relevance: 0.9,
      quality: 0.4,
      releaseConfidence: 0.75,
      identityConfidence: 0.8,
      providerAvailability: 0,
      episodeMatch: 1,
    },
    providers: {},
    media: [],
    _source: 'corpus',
  },
];
